### ISSUE TITLE
rock5c onboard wifi: mac address changes after reboot 

### ISSUE THREAD

**Issue by amazingfate** [radxa-pkg/aic8800#8]
Tested with v6.1 rk vendor kernel and v6.8.5 mainline kernel.
Mainline kernel need patches to compile, I will create a pr later.

**Comment by RadxaYuntian** [comment]
Probably because the eFUSE was not programmed?

**Comment by amazingfate** [comment]
It seems like you are maintaining patches in debian/patches, here is my patch to USB driver code to build under kernel v6.8: https://paste.armbian.com/aqazicigaj

**Comment by amazingfate** [comment]
> Probably because the eFUSE was not programmed?

There is kernel log: `AICWFDBG(LOGERROR)       no mac address in efuse!`.

**Comment by RadxaYuntian** [comment]
> https://paste.armbian.com/aqazicigaj

Rendering `>=` as `≥` is so trippy. That's certainly a bad UX to keep user guessing if someone uses a Unicode keyboard.

**Comment by RadxaYuntian** [comment]
![image](https://github.com/radxa-pkg/aic8800/assets/95260730/d7aa2536-04b1-438c-b26d-3089720a3a43)
You can just upload the patch to GitHub issue. I does not feel confident to copy past this page into a patch file.

**Comment by amazingfate** [comment]
Here is the raw file: https://paste.armbian.com/raw/aqazicigaj

**Comment by amazingfate** [comment]
Back to the mac address issue, I tried to set cloned mac address in NetworkManager to get static mac address, but After reboot the mac address is not set:
```
jfliu@rock-5c:~$ ip a show wlx880033771104
3: wlx880033771104: <NO-CARRIER,BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state DORMANT group default qlen 1000
    link/ether 88:00:33:77:11:04 brd ff:ff:ff:ff:ff:ff
jfliu@rock-5c:~$ nmcli -f 802-11-wireless.cloned-mac-address c s 202_5G
802-11-wireless.cloned-mac-address:     88:00:33:77:FC:92
```
I can use this method to let other wifi card like QCA6390 have static mac addredd, but it won't work for aic8800.
Here is the wifi driver log: https://paste.armbian.com/icixiyonir

**Comment by Anaple** [comment]
Similarly, I also encountered this problem when using the rk-5.10 kernel.

Is there any solution?

Kernel: https://github.com/Joshua-Riek/linux-rockchip

System version:

Ubuntu22.04

board : rock5 lite

**Comment by amazingfate** [comment]
Create an udev rule to get static wifi interface name:
```
$ cat /etc/udev/rules.d/99-radxa-aic8800.rules 
SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="88:00:*", NAME="$ENV{ID_NET_SLOT}"
```
Then use networkmanager to set cloned mac address.
