### ISSUE TITLE
请问可以用在stm32上面吗？

### ISSUE THREAD

**Issue by snikeguo** [radxa-pkg/aic8800#9]
我在做一个高速工控转wifi的项目，我会把多路串口，485，can总线，百兆以太网等数据汇总到单片机，然后通过wifi给电脑传。
我用的stm32h7 ，arm m7架构，主频550mhz，可以跑一个rtos，然后也有sdio接口。之所以不用esp32，是因为esp32速度太慢。我的想法是stm32h7我可以外扩一个32m字节的sdram作为备用，通过sdio操作8800d，把数据发出去。
所以问题就来了:我可以提供sdio接口，和freertos相关的资源接口，比如队列，信号量互斥锁啥的，能否驱动8800？请问你们有没有8800d的单片机驱动包？非常感谢。
对了，我没法用8800m，因为这个芯片没有can接口，没有以太网，所以没法用。如果也开发8800m固件，通过sdio和stm32h7通讯的话。那就和esp32s3没啥区别了。

**Comment by RadxaYuntian** [comment]
我们不是AIC8800的开发厂商也不是他们的经销商。我们这里提供的驱动仅限于服务我们自己的产品。

如果需要其他平台的商业支持请直接联系[爱科微](https://www.aicsemi.com/)。
